#!/bin/bash
nohup python vm-scheduler.py -m 8 -l logconf/vm-scheduler008.log.conf&
nohup python vm-scheduler.py -m 11 -l logconf/vm-scheduler011.log.conf&
nohup python vm-scheduler.py -m 12 -l logconf/vm-scheduler012.log.conf&
nohup python vm-scheduler.py -m 13 -l logconf/vm-scheduler013.log.conf&
nohup python vm-scheduler.py -m 14 -l logconf/vm-scheduler014.log.conf&
nohup python vm-scheduler.py -m 15 -l logconf/vm-scheduler015.log.conf&
nohup python vm-scheduler.py -m 16 -l logconf/vm-scheduler016.log.conf&
nohup python vm-scheduler.py -m 18 -l logconf/vm-scheduler018.log.conf&
nohup python vm-scheduler.py -m 34 -l logconf/vm-scheduler034.log.conf&
nohup python vm-scheduler.py -m 35 -l logconf/vm-scheduler035.log.conf&
nohup python vm-scheduler.py -m 36 -l logconf/vm-scheduler036.log.conf&
nohup python vm-scheduler.py -m 17 -l logconf/vm-scheduler017.log.conf&
nohup python vm-scheduler.py -m 18 -l logconf/vm-scheduler018.log.conf&
nohup python vm-scheduler.py -m 19 -l logconf/vm-scheduler019.log.conf&
nohup python vm-scheduler.py -m 20 -l logconf/vm-scheduler020.log.conf&
nohup python vm-scheduler.py -m 22 -l logconf/vm-scheduler022.log.conf&
nohup python vm-scheduler.py -m 23 -l logconf/vm-scheduler023.log.conf&
nohup python vm-scheduler.py -m 24 -l logconf/vm-scheduler024.log.conf&
nohup python vm-scheduler.py -m 25 -l logconf/vm-scheduler025.log.conf&
nohup python vm-scheduler.py -m 28 -l logconf/vm-scheduler028.log.conf&
